import Image from "next/image";
import Link from "next/link";
import { Layout } from "../components/Layout";
import { Constants } from "../models/constants";

export default function Terms() {
  const title = "Terms | Skeleton Crew | Skull NFTs for Solana";

  return (
    <Layout title={title}>
      <main id="terms">
        <section id="top">
          <div id="intro">
            <div id="intro-left">
              <div id="intro-left-container">
                <div id="mini-skull-container">
                  <div id="mini-skull">
                    <Link href="/" passHref={true}>
                      <Image
                        id="mini-skull-img"
                        src="/images/logos/1.png"
                        alt="Skeleton Crew Skull"
                        width="112"
                        height="112"
                        unoptimized
                      />
                    </Link>
                  </div>
                </div>
                <h1 id="welcome">
                  WELCOME
                  <br />
                  TO THE
                  <br />
                  SKELETON CREW
                </h1>
              </div>
            </div>
          </div>
          <div className="clear-both" />
        </section>
        <section id="tos">
          <div id="skulls-row-2-mobile">
            <Image
              src="/images/skulls-row-2-mobile.png"
              className="w-full"
              width="428"
              height="250"
              layout="responsive"
              alt="Row of Skulls"
              loading="eager"
            />
          </div>
          <div id="skulls-row-2">
            <Image
              src="/images/skulls-row-2.png"
              className="w-full"
              width="3840"
              height="1154"
              layout="responsive"
              alt="Row of Skulls"
              loading="eager"
            />
          </div>
          <h4>Terms</h4>
          <h5>TERMS &amp; CONDITIONS</h5>
          <p>
            The Skeleton Crew is a collection of digital artworks (NFTs) running
            on the Solana network. This website (www.skeletoncrew.rip) is only
            an interface allowing participants to exchange digital collectibles.
            Users are entirely responsible for the safety and management of
            their own private Solana wallets and validating all transactions and
            contracts generated by this website before approval. Furthermore, as
            the The Skeleton Crew smart contract runs on the Solana network,
            there is no ability to undo, reverse, or restore any transactions.
          </p>
          <p>
            This website and its connected services are provided “as is” and “as
            available” without warranty of any kind. By using this website you
            are accepting sole responsibility for any and all transactions
            involving The Skeleton Crew digital collectibles.
          </p>

          <h5>1. OWNERSHIP</h5>
          <p>
            A. You Own the NFT. Each SKULL is an NFT on the Solana blockchain.
            When you purchase an NFT, you own the underlying SKULL, the Art,
            completely. Ownership of the NFT is mediated entirely by the Smart
            Contract and the Solana Network: at no point may we seize, freeze,
            or otherwise modify the ownership of any SKULL.
          </p>
          <p>
            B. Personal Use. Subject to your continued compliance with these
            Terms, The Skeleton Crew grants you a worldwide, non-exclusive,
            royalty-free license to use, copy, and display the purchased Art,
            along with any extensions that you choose to create or use, solely
            for the following purposes: (i) for your own personal,
            non-commercial use; (ii) as part of a marketplace that permits the
            purchase and sale of your SKULL / NFT, provided that the marketplace
            cryptographically verifies each SKULL owner’s rights to display the
            Art for their SKULL to ensure that only the actual owner can display
            the Art; or (iii) as part of a third party website or application
            that permits the inclusion, involvement, or participation of your
            SKULL, provided that the website/application cryptographically
            verifies each SKULL owner’s rights to display the Art for their
            SKULL to ensure that only the actual owner can display the Art, and
            provided that the Art is no longer visible once the owner ofthe
            SKULL leaves the website/application.
          </p>
          <p>
            C. Commercial Use. Subject to your continued compliance with these
            Terms, The Skeleton Crew grants you an unlimited, non-exclusive,
            worldwide license to use, copy, and display the purchased Art for
            the purpose of creating derivative works based upon the Art
            (“Commercial Use”). Examples of such Commercial Use would e.g. be
            the use of the Art to produce and sell merchandise products
            (T-Shirts etc.) displaying copies of the Art. For the sake of
            clarity, nothing in this Section will be deemed to restrict you from
            (i) owning or operating a marketplace that permits the use and sale
            of SKULLS generally, provided that the marketplace cryptographically
            verifies each SKULL owner’s rights to display the Art for their
            SKULL to ensure that only the actual owner can display the Art; (ii)
            owning or operating a third party website or application that
            permits the inclusion, involvement, or participation of SKULLS
            generally, provided that the third party website or application
            cryptographically verifies each SKULL owner’s rights to display the
            Art for their SKULL to ensure that only the actual owner can display
            the Art, and provided that the Art is no longer visible once the
            owner of the Purchased SKULL leaves the website/application; or
            (iii) earning revenue from any of the foregoing.
          </p>
          <p>
            D. The Skeleton Crew IP. Other than the rights to the Art, nothing
            herein gives you any rights to any other trademarks or other
            intellectual property rights belonging to the Skeleton Crew
            including, without limitation, to the Skeleton Crew, Skeleton Crew
            Skulls, and the associated logos. All of these rights are expressly
            reserved in the name of The Skeleton Crew.
          </p>
          <p>
            E. Feedback. You may choose to submit comments, bug reports, ideas
            or other feedback about the Site, including without limitation about
            how to improve the Site (collectively, “Feedback”). By submitting
            any Feedback, you agree that we are free to use such Feedback in any
            way we choose without additional compensation to you and you hereby
            grant us a perpetual, irrevocable, nonexclusive, worldwide license
            to incorporate and use the Feedback for any purpose.
          </p>

          <h5>2. Your Obligations</h5>
          <p>
            You are solely responsible for your own conduct while accessing or
            using the Site, and for any consequences thereof. You agree to use
            the Site only for purposes that are legal, proper and in accordance
            with these Terms and any applicable laws or regulations. By way of
            example, and not as a limitation, you may not, and may not allow any
            third party to: (i) send, upload, distribute or disseminate any
            unlawful, defamatory, harassing, abusive, fraudulent, hateful,
            violent, obscene, or otherwise objectionable content; (ii)
            distribute viruses, worms, defects, Trojan horses, corrupted files,
            hoaxes, or any other items of a destructive or deceptive nature;
            (iii) impersonate another person; (iv) upload, post, transmit or
            otherwise make available through the Site any content that infringes
            the intellectual property or proprietary rights of any party or
            otherwise violates the legal rights of others; (v) engage in,
            promote, or encourage illegal activity (including, without
            limitation, money laundering); (vi) interfere with other users‘ use
            of the Site; (vii) use the Site for any unauthorized commercial
            purpose; (viii) modify, adapt, translate, or reverse engineer any
            portion of the Site; (ix) remove any copyright, trademark or other
            proprietary rights notices contained in or on the Site or any part
            of it; (x) use any technology to collect information about the
            Site’s for any unauthorized purpose; (xi) access or use the Site for
            the purpose of creating a product or service that is competitive
            with any of our products or services. If you engage in any of the
            activities prohibited by this Section, we may, at our sole and
            absolute discretion, without notice to you, and without limiting any
            of our other rights or remedies at law or in equity, immediately
            suspend or terminate your user account.
          </p>

          <h5>3. Fees and Payment</h5>
          <p>
            A. If you elect to purchase a SKULL through the Site, any financial
            transactions that you engage in will be conducted solely through the
            Solana network. We will have no insight into or control over these
            payments or transactions, nor do we have the ability to reverse any
            transactions. We will have no liability to you or to any third party
            for any claims or damages that may arise as a result of any
            transactions that you engage or any other transactions that you
            conduct via the Solana network.
          </p>
          <p>
            B. Solana requires the payment of a transaction fee for every
            transaction that occurs on the Solana network. The fee funds the
            network of computers that run the decentralized Solana network. This
            means that you will need to pay a fee for each transaction.
          </p>

          <h5>4. Disclaimers</h5>
          <p>
            A. YOU EXPRESSLY UNDERSTAND AND AGREE THAT YOUR ACCESS TO AND USE OF
            THE SITE IS AT YOUR SOLE RISK, AND THAT THE SITE IS PROVIDED “AS IS”
            AND “AS AVAILABLE” WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS
            OR IMPLIED. TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE
            LAW, WE MAKE NO EXPRESS WARRANTIES AND HEREBY DISCLAIM ALL IMPLIED
            WARRANTIES REGARDING THE SITE AND ANY PART OF IT (INCLUDING, WITHOUT
            LIMITATION, THE SITE, ANY SMART CONTRACT, OR ANY EXTERNAL WEBSITES),
            INCLUDING THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
            PARTICULAR PURPOSE, NON-INFRINGEMENT, CORRECTNESS, ACCURACY, OR
            RELIABILITY. WITHOUT LIMITING THE GENERALITY OF THE FOREGOING, WE,
            OUR SUBSIDIARIES, AFFILIATES, AND LICENSORS DO NOT REPRESENT OR
            WARRANT TO YOU THAT: (I) YOUR ACCESS TO OR USE OF THE SITE WILL MEET
            YOUR REQUIREMENTS, (II) YOUR ACCESS TO OR USE OF THE SITE WILL BE
            UNINTERRUPTED, TIMELY, SECURE OR FREE FROM ERROR, (III) USAGE DATA
            PROVIDED THROUGH THE SITE WILL BE ACCURATE, (III) THE SITE OR ANY
            CONTENT, SERVICES, OR FEATURES MADE AVAILABLE ON OR THROUGH THE SITE
            ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS, OR (IV) THAT ANY
            DATA THAT YOU DISCLOSE WHEN YOU USE THE SITE WILL BE SECURE. SOME
            JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES IN
            CONTRACTS WITH CONSUMERS, SO SOME OR ALL OF THE ABOVE EXCLUSIONS MAY
            NOT APPLY TO YOU.
          </p>
          <p>
            B. YOU ACCEPT THE INHERENT SECURITY RISKS OF PROVIDING INFORMATION
            AND DEALING ONLINE OVER THE INTERNET, AND AGREE THAT WE HAVE NO
            LIABILITY OR RESPONSIBILITY FOR ANY BREACH OF SECURITY UNLESS IT IS
            DUE TO OUR WILLFULL MISCONDUCT.
          </p>
          <p>
            C. WE WILL NOT BE RESPONSIBLE OR LIABLE TO YOU FOR ANY LOSSES YOU
            INCUR AS THE RESULT OF YOUR USE OF THE SOLANA NETWORK NOR DO WE HAVE
            ANY CONTROL OVER AND MAKE NO GUARANTEES REGARDING ANY SMART
            CONTRACTS.
          </p>

          <h5>5. Limitation of Liability</h5>
          <p>
            A. YOU UNDERSTAND AND AGREE THAT WE WILL NOT BE LIABLE TO YOU OR TO
            ANY THIRD PARTY FOR ANY INDIRECT, INCIDENTAL, SPECIAL,
            CONSEQUENTIAL, OR EXEMPLARY DAMAGES WHICH YOU MAY INCUR, HOWSOEVER
            CAUSED AND UNDER ANY THEORY OF LIABILITY, INCLUDING, WITHOUT
            LIMITATION, ANY LOSS OF PROFITS (WHETHER INCURRED DIRECTLY OR
            INDIRECTLY), LOSS OF GOODWILL OR BUSINESS REPUTATION, LOSS OF DATA,
            COST OF PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES, OR ANY OTHER
            INTANGIBLE LOSS, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF
            SUCH DAMAGES.
          </p>
          <p>
            B. YOU AGREE THAT OUR TOTAL, AGGREGATE LIABILITY TO YOU FOR ANY AND
            ALL CLAIMS ARISING OUT OF OR RELATING TO THESE TERMS OR YOUR ACCESS
            TO OR USE OF (OR YOUR INABILITY TO ACCESS OR USE) ANY PORTION OF THE
            SITE, WHETHER IN CONTRACT, TORT, STRICT LIABILITY, OR ANY OTHER
            LEGAL THEORY, IS LIMITED TO THE GREATER OF (A) THE AMOUNTS YOU
            ACTUALLY PAID US UNDER THESE TERMS IN THE 12 MONTH PERIOD PRECEDING
            THE DATE THE CLAIM AROSE, OR (B) $500.
          </p>
          <p>
            C. YOU ACKNOWLEDGE AND AGREE THAT WE HAVE MADE THE SITE AVAILABLE TO
            YOU AND ENTERED INTO THESE TERMS IN RELIANCE UPON THE WARRANTY
            DISCLAIMERS AND LIMITATIONS OF LIABILITY SET FORTH HEREIN. WE WOULD
            NOT BE ABLE TO PROVIDE THE SITE TO YOU WITHOUT THESE LIMITATIONS.
          </p>

          <h5>6. Risk Assumption</h5>
          <p>You accept and acknowledge each of the following:</p>
          <p>
            A. To the extent that you sell your Skeleton Crew NFT, please be
            aware that the prices of NFTs are extremely volatile and
            fluctuations in the prices of other NFTs and impact the price of
            your Skeleton Crew SKULL NFT both positively and negatively. Given
            the volatility, NFTs such as the Skeleton Crew SKULL should not be
            considered an investment. You assume all risks in that connection.
          </p>
          <p>
            B. Ownership of a Skeleton Crew SKULL confers ownership of digital
            artwork only. Accordingly, no information on this Site (or any other
            documents mentioned therein) is or may be considered to be advice or
            an invitation to enter into an agreement for any investment purpose.
            Further, nothing on this Site qualifies or is intended to be an
            offering of securities in any jurisdiction nor does it constitute an
            offer or an invitation to purchase shares, securities or other
            financial products. Due to the artistic nature of the project, the
            Skeleton Crew has not been registered with or approved by any
            regulator in any jurisdiction. It remains your sole responsibility
            to assure that the purchase of the Skeleton Crew SKULL NFT and the
            associated art is in compliance with laws and regulations in your
            jurisdiction.
          </p>
          <p>
            C. You assume all risks associated with using an Internet-based
            currency, including, but not limited to, the risk of hardware,
            software and Internet connections, the risk of malicious software
            introduction, and the risk that third parties may obtain
            unauthorized access to information stored within your wallet.
          </p>
          <p>
            D. NFTs, cryptocurrencies and blockchain technology are relatively
            new and the regulatory landscape is unsettled. New regulations could
            negatively impact such technologies impacting the value for your
            Skeleton Crew SKULL. You understand and accept all risk in that
            regard.
          </p>
          <p>
            E. You assume all responsibility for any adverse effects of
            disruptions or other issues impacting Solana or the Solana network.
          </p>

          <h5>7. Indemnification</h5>
          <p>
            You agree to hold harmless and indemnify the Skeleton Crew and its
            subsidiaries, affiliates, officers, agents, employees, advertisers,
            licensors, suppliers or partners from and against any claim,
            liability, loss, damage (actual and consequential) of any kind or
            nature, suit, judgment, litigation cost, and reasonable attorneys‘
            fees arising out of or in any way related to (i) your breach of
            these Terms, (ii) your misuse of the Site, or (iii) your violation
            of applicable laws, rules or regulations in connection with your
            access to or use of the Site.
          </p>

          <h5>8. Changes to the Terms and Conditions</h5>
          <p>
            We may make changes to the Terms at our discretion. Please check
            these Terms periodically for changes. Any changes to the Terms will
            apply on the date that they are made, and your continued access to
            or use after the Terms have been updated will constitute your
            binding acceptance of the updates. If you do not agree to any
            revised Terms, you may not access or use the Site.
          </p>

          <h5>9. Children</h5>
          <p>
            Our Site is not intended for children. You must be at least 18 years
            old to access this Site or purchase a Skeleton Crew SKULL. If you
            are under 18 years old you are not permitted to use this Site for
            any reason. By accessing the Site, you represent and warrant that
            you are at least 18 years of age.
          </p>

          <h5>10. Dispute Resolution; Arbitration</h5>
          <p>
            All disputes arising out of or in connection with these Terms,
            including without limitation your access or use of the Site, or to
            any products sold or distributed through the Site, will be referred
            to and finally resolved by arbitration under the rules of the
            American Arbitration Association. The case will be adjudicated by a
            single arbitrator and will be administered by the American
            Arbitration Association in accordance with its applicable rules.
            Each party will cover its own fees and costs associated with the
            arbitration proceedings. The place of arbitration will be New York,
            New York. The award of the arbitrator will be final and binding, and
            any judgment on the award rendered by the arbitrator may be entered
            in any court of competent jurisdiction. Notwithstanding the
            foregoing, we may seek and obtain injunctive relief in any
            jurisdiction in any court of competent jurisdiction.
          </p>

          <p>
            WITH RESPECT TO ANY DISPUTE ARISING OUT OF OR RELATED TO THESE
            TERMS, INCLUDING WITHOUT LIMITATION DISPUTES RELATED TO THE SITE OR
            ANY PRODUCTS SOLD OR DISTRIBUTED THROUGH THE SITE, OR THE SMART
            CONTRACTS: (I) YOU HEREBY EXPRESSLY GIVE UP YOUR RIGHT TO HAVE A
            TRIAL BY JURY; AND (II) YOU HEREBY EXPRESSLY GIVE UP YOUR RIGHT TO
            PARTICIPATE AS A MEMBER OF A CLASS OF CLAIMANTS IN ANY LAWSUIT,
            INCLUDING BUT NOT LIMITED TO CLASS ACTION LAWSUITS INVOLVING ANY
            SUCH DISPUTE.
          </p>

          <h5>11. Notice of Non-Affiliation and Disclaimer</h5>
          <p>
            We are not affiliated, associated, authorized, endorsed by, or in
            any way officially connected with Solana, or any of its subsidiaries
            or its affiliates. The names Solana, the Solana blockchain, and the
            Solana network, as well as related names, marks, emblems and images
            are registered trademarks of their respective owners.
          </p>
        </section>
        <section id="social">
          <h4 className="druk">JOIN US</h4>
          <Link href={Constants.twitterURL} passHref={true}>
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="80"
              height="65.013"
              viewBox="0 0 80 65.013"
            >
              <path
                d="M80,9.945a32.769,32.769,0,0,1-9.427,2.583,16.44,16.44,0,0,0,7.217-9.08A32.879,32.879,0,0,1,67.367,7.431,16.424,16.424,0,0,0,39.4,22.4,46.594,46.594,0,0,1,5.57,5.251a16.435,16.435,0,0,0,5.077,21.913,16.343,16.343,0,0,1-7.43-2.053,16.425,16.425,0,0,0,13.163,16.3,16.451,16.451,0,0,1-7.413.28A16.425,16.425,0,0,0,24.3,53.088,33,33,0,0,1,0,59.888a46.464,46.464,0,0,0,25.16,7.373c30.473,0,47.69-25.737,46.65-48.82A33.416,33.416,0,0,0,80,9.945Z"
                transform="translate(0 -2.248)"
              />
            </svg>
          </Link>

          <Link href={Constants.discordInviteURL} passHref={true}>
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="80"
              height="60.632"
              viewBox="0 0 80 60.632"
              id="social-discord"
            >
              <path
                d="M-118.232-43.1a66.183,66.183,0,0,0-16.5-5.078,45.316,45.316,0,0,0-2.114,4.3,61.462,61.462,0,0,0-18.317,0,45.46,45.46,0,0,0-2.114-4.3A66.644,66.644,0,0,0-173.8-43.09c-10.445,15.454-13.277,30.524-11.861,45.38h0a66.518,66.518,0,0,0,20.242,10.162,48.848,48.848,0,0,0,4.335-6.991A43.038,43.038,0,0,1-167.91,2.2c.573-.415,1.133-.843,1.674-1.258a47.551,47.551,0,0,0,40.472,0c.547.447,1.107.875,1.674,1.258a43.2,43.2,0,0,1-6.84,3.266,48.425,48.425,0,0,0,4.335,6.984A66.227,66.227,0,0,0-106.34,2.3h0C-104.679-14.932-109.178-29.863-118.232-43.1ZM-159.289-6.846c-3.945,0-7.2-3.58-7.2-7.985s3.146-8.016,7.192-8.016,7.28,3.612,7.211,8.016S-155.269-6.846-159.289-6.846Zm26.579,0c-3.952,0-7.2-3.58-7.2-7.985s3.146-8.016,7.2-8.016,7.261,3.612,7.192,8.016S-128.69-6.846-132.711-6.846Z"
                transform="translate(186 48.18)"
              />
            </svg>
          </Link>
        </section>
        <section id="skulls-banner-bottom-section">
          <div id="skulls-banner-bottom" className="skulls-banner">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="2039.1"
              height="231.6"
              viewBox="0 0 2039.1 231.6"
              preserveAspectRatio="xMidYMax meet"
            >
              <path
                d="M-833.1,4.5c126.9,0,152.4-38.4,152.4-78v-4.2c0-45.3-30.6-66.3-117.6-68.7l-45-1.2c-34.5-.9-43.2-5.4-43.2-13.5v-.6c0-7.5,5.1-11.7,32.4-11.7,29.7,0,33.3,10.8,34.2,18h130.8v-1.5c0-38.4-27.9-70.2-147.6-70.2h-38.1c-108,0-141.6,25.8-141.6,67.8v2.7c0,35.1,19.2,67.5,111,70.8l47.1,1.5c38.4,1.5,41.4,8.4,41.4,15.9v.9c0,8.1-7.8,15.6-34.2,15.6-31.2,0-35.4-14.4-35.4-24H-1020v2.4c0,28.8,12.3,78,147.6,78ZM-540.3,0V-89.1L-448.5,0h148.8L-432.9-123l132.6-100.2H-438.9L-540.3-144v-79.2h-114V0Zm251.7-119.7C-288.6-75-272.1,3.9-123.3,3.9h15C40.5,3.9,57.6-75,57.6-119.7V-223.2H-57v91.8c0,24.9-11.4,51.3-58.2,51.3h-.6c-47.7,0-58.2-26.4-58.2-51.3v-91.8H-288.6ZM89.1-223.2V0H357.9V-79.5H203.1V-223.2Zm299.4,0V0H657.3V-79.5H502.5V-223.2ZM866.7,4.5c126.9,0,152.4-38.4,152.4-78v-4.2c0-45.3-30.6-66.3-117.6-68.7l-45-1.2c-34.5-.9-43.2-5.4-43.2-13.5v-.6c0-7.5,5.1-11.7,32.4-11.7,29.7,0,33.3,10.8,34.2,18h130.8v-1.5c0-38.4-27.9-70.2-147.6-70.2H825c-108,0-141.6,25.8-141.6,67.8v2.7c0,35.1,19.2,67.5,111,70.8l47.1,1.5c38.4,1.5,41.4,8.4,41.4,15.9v.9c0,8.1-7.8,15.6-34.2,15.6-31.2,0-35.4-14.4-35.4-24H679.8v2.4c0,28.8,12.3,78,147.6,78Z"
                transform="translate(1020 227.1)"
              />
            </svg>
          </div>
        </section>
        <section id="footer">
          <ul>
            <li>THE SKELETON CREW 2021 • ALL RIGHTS RESERVED</li>
            <li>
              <Link href="/terms" passHref={true}>
                TERMS
              </Link>
            </li>
            <li>
              <Link
                href={Constants.discordInviteURL}
                passHref={true}
                target="_blank"
              >
                JOIN OUR DISCORD
              </Link>
            </li>
          </ul>
        </section>
      </main>
      <script src="/js/scripts.js" async></script>
    </Layout>
  );
}
